version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    #image: tensorflow/tensorflow:latest
    ports:
      - "5000:5000"
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
