version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
  backend:
    container_name: backend
    build: ./backend
  frontend:
    container_name: frontend
    build: ./frontend
